spring:
  application:
    name: movie-service
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/movie-dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      dataLocations: classpath:/movie-service.sql

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true